### PR TITLE
Update function documentation, minor changes to README

### PR DESCRIPTION
**Pull request by everittB**
- Added in function documentation 
- Updated usage instructions for `rotate` on the README

### CODE REVIEW

**Comment by alyciakb** [comment]
- I updated the installation directions to be in compliance with the milestone2 directions 
- Fixed a couple spelling typos

**Comment by alyciakb** [comment]
TO DO: 
- In rotate.py, change the output to include the original image as the first image in the returned array. 
- Change any corresponding `test_rotate.py` tests to reflect that change

**Review by alyciakb — CHANGES_REQUESTED** [review]
* In rotate.py, change the output to include the original image as the first image in the returned array.
* Change any corresponding `test_rotate.py` tests to reflect that change

**Comment by everittB** [comment]
Addressed feedback. fad71569dbfda05407683421387c96a22290b80c

**Pull request merged**
